# VALORES DE CONSTANTE, OU SEJA, VALORES QUE POSSO ALTERAR A IMAGEM A QUALQUER MOMENTO

# C
COLOR_RED = 255, 0, 0
COLOR_GRAY = (128, 128, 128)
COLOR_YELLOW = (255, 255, 0)

# W
WIN_WIDTH = 576  # LARGURA DA JANELA
WIN_HEIGHT = 324  # ALTURA DA JANELA


# M
MENU_OPTION = ('NEW GAME 1P',
               'NEW GAME 2P - COOPERATIVE',
               'NEW GAME 2P - COMPETITIVE'
               'SCORE',
               'EXIT')
